stages:
  data_ingestion:
    cmd: python src/gslTranslater/pipeline/stage_01_data_ingestion.py
    deps:
      - src/gslTranslater/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    params:
      - MAX_INSTANCES_PER_CLASS
      - TRAIN_SPLIT
      - TEST_SPLIT
      - VALIDATE_SPLIT
      - NUM_UNIQUE_WORDS
    outs:
      - artifacts/data_ingestion/GSL_isolated
      - artifacts/data_ingestion/GSL_Analysis

  prepare_base_model:
    cmd: python src/gslTranslater/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/gslTranslater/pipeline/stage_02_prepare_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model

  training:
    cmd: python src/gslTranslater/pipeline/stage_03_model_training.py
    deps:
      - src/gslTranslater/pipeline/stage_03_model_training.py
      - config/config.yaml
      - artifacts/data_ingestion/GSL_isolated
      - artifacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
      - MAX_SEQ_LENGTH
    outs:
      - artifacts/training/cnn_lstm_model_trained.pth

  evaluation:
    cmd: python src/gslTranslater/pipeline/stage_04_model_evaluation.py
    deps:
      - src/gslTranslater/pipeline/stage_04_model_evaluation.py
      - config/config.yaml
      - artifacts/data_ingestion/GSL_isolated
      - artifacts/training/cnn_lstm_model_trained.pth
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
      - scores.json:
          cache: false
